from swebench.harness.constants import KEY_INSTANCE_ID

KEY_INSTANCE_ID = KEY_INSTANCE_ID
KEY_REPO = 'repo'
KEY_VERSION = 'version'
KEY_TEST_PATCH = 'test_patch'
CONDA_ENV_NAME = 'testbed'
HEREDOC_DELIMITER_REQUIREMENTS = 'EOF_59812759871'
HEREDOC_DELIMITER_GIT_APPLY = 'EOF_114329324912'

KAGGLE_INPUT_DIR = '/kaggle/input'
KAGGLE_WORKING_DIR = '/kaggle/working'
KAGGLE_OUTPUT_DIR = f'{KAGGLE_WORKING_DIR}/output'
KAGGLE_EVAL_PYTHON_VERSION = "3.11"

KAGGLE_DOCKER_IMAGE_TAG = "latest"  # "v153" - last version that supports conda
KAGGLE_DOCKER_IMAGE = 'gcr.io/kaggle-images/python'
KAGGLE_DOCKER_IMAGE_WORKING = f'{KAGGLE_DOCKER_IMAGE}:{KAGGLE_DOCKER_IMAGE_TAG}'
