from enum import Enum


class FailureMode(Enum):
    UNKNOWN = "UNKNOWN"
    NO_FAIL_TO_PASS = "NO_FAIL_TO_PASS"
    NO_TO_PASS = "NO_TO_PASS"
    NO_TESTS_RUN = "NO_TESTS_RUN"
    TIMEOUT = "TIMEOUT"
    APPLY_PATCH_FAILURE = "APPLY_PATCH_FAILURE"
    RUN_INSTANCE_FAILURE = "RUN_INSTANCE_FAILURE"
    BUILD_IMAGE_FAILURE = "BUILD_IMAGE_FAILURE"
    DUPLICATE_INSTANCE = "DUPLICATE_INSTANCE"
    SUCCESS = "SUCCESS"
